_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[ 2.84512654e-17 -1.13318334e-01  6.34924116e-17  1.73482690e-18
          -1.09193272e-02  2.60396732e+00  1.98865558e+01  7.64098087e-20
          -1.73106559e-01 -1.77581988e+01  1.27149133e+01  4.70284866e+01
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  2.80000001e-01  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00 -5.15857740e-16
          -1.13318334e-01 -1.48609303e-15 -2.73235236e-17  8.67361738e-18
          -3.21422690e+00 -3.97197160e+01  1.44322640e+00  4.33729814e-01
          -3.98349770e+01  3.41462401e+00 -5.31625665e+00  2.80000001e-01
           0.00000000e+00]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7bc14275ee50>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 1000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.25.1
        e:
            m7f5su9b0kz8379ayw1rxa9t0bqoe2r4:
                args:
                    - --env
                    - dogfight_FW
                    - --total_timesteps
                    - "5000"
                    - --update_interval
                    - "1000"
                codePath: test_ma_envs.py
                codePathLocal: test_ma_envs.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "982838722560"
                        used: "70187589632"
                email: vbeimuk@uwaterloo.ca
                executable: /home/volodymyr/work/UAV-MARL-Lib/.venv/bin/python
                git:
                    commit: 930549c055a6b557482e92029e003a00f87b6fdf
                    remote: https://github.com/CL2-UWaterloo/UAV-MARL-Lib.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-414732cf-99de-5024-b560-b7730651fc23
                host: vldmr3
                memory:
                    total: "63040970752"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: /home/volodymyr/work/UAV-MARL-Lib/test_ma_envs.py
                python: CPython 3.11.15
                root: /home/volodymyr/work/UAV-MARL-Lib
                startedAt: "2026-04-01T15:44:07.997147Z"
                writerId: m7f5su9b0kz8379ayw1rxa9t0bqoe2r4
        m: []
        python_version: 3.11.15
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 3
                - 13
                - 16
                - 22
            "4": 3.11.15
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Box(-1.0, 1.0, (4,), float64)
actor:
    value: |-
        Actor(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (latent_pi): Sequential(
            (0): Linear(in_features=37, out_features=256, bias=True)
            (1): ReLU()
            (2): Linear(in_features=256, out_features=256, bias=True)
            (3): ReLU()
          )
          (mu): Linear(in_features=256, out_features=4, bias=True)
          (log_std): Linear(in_features=256, out_features=4, bias=True)
        )
algo:
    value: SAC
batch_norm_stats:
    value: '[]'
batch_norm_stats_target:
    value: '[]'
batch_size:
    value: 256
buffer_size:
    value: 1000000
checkpoint_freq:
    value: 1000
critic:
    value: |-
        ContinuousCritic(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (qf0): Sequential(
            (0): Linear(in_features=41, out_features=256, bias=True)
            (1): ReLU()
            (2): Linear(in_features=256, out_features=256, bias=True)
            (3): ReLU()
            (4): Linear(in_features=256, out_features=1, bias=True)
          )
          (qf1): Sequential(
            (0): Linear(in_features=41, out_features=256, bias=True)
            (1): ReLU()
            (2): Linear(in_features=256, out_features=256, bias=True)
            (3): ReLU()
            (4): Linear(in_features=256, out_features=1, bias=True)
          )
        )
critic_target:
    value: |-
        ContinuousCritic(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (qf0): Sequential(
            (0): Linear(in_features=41, out_features=256, bias=True)
            (1): ReLU()
            (2): Linear(in_features=256, out_features=256, bias=True)
            (3): ReLU()
            (4): Linear(in_features=256, out_features=1, bias=True)
          )
          (qf1): Sequential(
            (0): Linear(in_features=41, out_features=256, bias=True)
            (1): ReLU()
            (2): Linear(in_features=256, out_features=256, bias=True)
            (3): ReLU()
            (4): Linear(in_features=256, out_features=1, bias=True)
          )
        )
device:
    value: cuda
ent_coef:
    value: auto
ent_coef_optimizer:
    value: |-
        Adam (
        Parameter Group 0
            amsgrad: False
            betas: (0.9, 0.999)
            capturable: False
            decoupled_weight_decay: False
            differentiable: False
            eps: 1e-08
            foreach: None
            fused: None
            lr: 0.0003
            maximize: False
            weight_decay: 0
        )
env:
    value: dogfight_FW
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gamma:
    value: 0.99
gradient_steps:
    value: 1
learning_rate:
    value: 0.0003
learning_starts:
    value: 100
log_ent_coef:
    value: tensor([0.], device='cuda:0', requires_grad=True)
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
n_envs:
    value: 1
n_steps:
    value: 1
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (37,), float64)
optimize_memory_usage:
    value: "False"
policy:
    value: |-
        SACPolicy(
          (actor): Actor(
            (features_extractor): FlattenExtractor(
              (flatten): Flatten(start_dim=1, end_dim=-1)
            )
            (latent_pi): Sequential(
              (0): Linear(in_features=37, out_features=256, bias=True)
              (1): ReLU()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): ReLU()
            )
            (mu): Linear(in_features=256, out_features=4, bias=True)
            (log_std): Linear(in_features=256, out_features=4, bias=True)
          )
          (critic): ContinuousCritic(
            (features_extractor): FlattenExtractor(
              (flatten): Flatten(start_dim=1, end_dim=-1)
            )
            (qf0): Sequential(
              (0): Linear(in_features=41, out_features=256, bias=True)
              (1): ReLU()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): ReLU()
              (4): Linear(in_features=256, out_features=1, bias=True)
            )
            (qf1): Sequential(
              (0): Linear(in_features=41, out_features=256, bias=True)
              (1): ReLU()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): ReLU()
              (4): Linear(in_features=256, out_features=1, bias=True)
            )
          )
          (critic_target): ContinuousCritic(
            (features_extractor): FlattenExtractor(
              (flatten): Flatten(start_dim=1, end_dim=-1)
            )
            (qf0): Sequential(
              (0): Linear(in_features=41, out_features=256, bias=True)
              (1): ReLU()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): ReLU()
              (4): Linear(in_features=256, out_features=1, bias=True)
            )
            (qf1): Sequential(
              (0): Linear(in_features=41, out_features=256, bias=True)
              (1): ReLU()
              (2): Linear(in_features=256, out_features=256, bias=True)
              (3): ReLU()
              (4): Linear(in_features=256, out_features=1, bias=True)
            )
          )
        )
policy_class:
    value: <class 'stable_baselines3.sac.policies.SACPolicy'>
policy_kwargs:
    value: '{''use_sde'': False}'
replay_buffer:
    value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x7bc14307aed0>
replay_buffer_class:
    value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1775058267023561851
target_entropy:
    value: -4
target_update_interval:
    value: 1
tau:
    value: 0.005
tensorboard_log:
    value: junk/save-dogfight_FW-0-04.01.2026_11.38/tb_logs/agent_0
timesteps:
    value: 5000
train_freq:
    value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
update_interval:
    value: 1000
use_sde:
    value: "False"
use_sde_at_warmup:
    value: "False"
verbose:
    value: 1
